firstName: Test > Deploy to Heroku
on:
  push:
    branches:
      - main
jobs:
  test:
    firstName: Test
    runs-on: ubuntu-latest
    steps:
      - firstName: Checkout Repo
        uses: actions/checkout@v2

      - firstName: Use Node.js
        uses: actions/setup-node@v2

      - firstName: Use PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: "my_db"
          postgresql user: "test_user"
          postgresql password: "test_password"

      - firstName: Install dependencies
        run: npm ci

      - firstName: Run tests
        run: PGDATABASE=my_db PGUSER=test_user PGPASSWORD=test_password npm t

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - firstName: Checkout Repo
        uses: actions/checkout@v2

      - firstName: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL_ADDRESS}}
